### ISSUE TITLE
Add all illustrations

### ISSUE THREAD

**Issue by andyroberson** [andyroberson/j584-coral-game#21]

**Comment by kristiwalker** [comment]
![co2-button](https://cloud.githubusercontent.com/assets/10449842/14538400/93d44db2-0249-11e6-88d3-ac8da3f22cfa.png)
![food-buttons](https://cloud.githubusercontent.com/assets/10449842/14538402/93d6ec98-0249-11e6-8690-e7987a38e2f7.png)
![light-buttons](https://cloud.githubusercontent.com/assets/10449842/14538401/93d6cf9c-0249-11e6-8d6d-23edc1907e98.png)
![temp-button](https://cloud.githubusercontent.com/assets/10449842/14538399/93d1c0ec-0249-11e6-9ca2-3ffb141e0508.png)

**Comment by kristiwalker** [comment]
![assets_lab table](https://cloud.githubusercontent.com/assets/10449842/14582160/9c80897a-03cb-11e6-9581-8e2c96e6acf7.png)

**Comment by kristiwalker** [comment]
![assets_tank](https://cloud.githubusercontent.com/assets/10449842/14582233/4d5b1cd2-03cd-11e6-9f92-da76fd4e91fb.png)

Sorry about all of the weird naming conventions. Export kind of gives it whatever name it wants and I figured I'd just let you rename it if you want since I don't know your preferences.

**Comment by kristiwalker** [comment]
![lights](https://cloud.githubusercontent.com/assets/10449842/14582236/5bd75730-03cd-11e6-826d-3b6d8db89f2b.png)

**Comment by kristiwalker** [comment]
1-dish tank

![tank](https://cloud.githubusercontent.com/assets/10449842/14659539/e1a262d4-066a-11e6-819e-d6a9b3dcc1ec.png)
