### ISSUE TITLE
changing illustrations based on actions

### ISSUE THREAD

**Issue by andyroberson** [andyroberson/j584-coral-game#25]
i.e sad coral if too hot / cold etc

**Comment by kristiwalker** [comment]
In case you prefer to have the files this way:

![coral-1-20](https://cloud.githubusercontent.com/assets/10449842/14475250/1d88dd74-00cf-11e6-8db2-fd6e1f583bb2.png)
![coral-1-30](https://cloud.githubusercontent.com/assets/10449842/14475251/1d89167c-00cf-11e6-902d-9c8e2607a7ca.png)
![coral-1-40](https://cloud.githubusercontent.com/assets/10449842/14475252/1d901f94-00cf-11e6-99b9-52036cab3552.png)
![coral-1-50](https://cloud.githubusercontent.com/assets/10449842/14475253/1d96a47c-00cf-11e6-8d30-cff87503f53b.png)
![coral-1-60](https://cloud.githubusercontent.com/assets/10449842/14475254/1d984fde-00cf-11e6-843a-07c91de0c37b.png)
![coral-1-70](https://cloud.githubusercontent.com/assets/10449842/14475255/1d9e8eee-00cf-11e6-81b9-abe20ccb9933.png)
![coral-1-80](https://cloud.githubusercontent.com/assets/10449842/14475256/1d9ee7ea-00cf-11e6-81e3-f7d41bd5a74f.png)
![coral-1-90](https://cloud.githubusercontent.com/assets/10449842/14475258/1dacd210-00cf-11e6-8382-e22aaba247fd.png)
![coral-1-100](https://cloud.githubusercontent.com/assets/10449842/14475257/1da93f7e-00cf-11e6-9852-ec0430a2a87f.png)

**Comment by kristiwalker** [comment]
Here's what I asked in my email, too:

Attached is the phasing for the coral. 

100-80 are the happy, pretty red versions of Big Red. 
70-50 are the discontent, slightly bleached versions.
40-20 are the very displeased, very bleached versions.

Can you explain why you wanted other variations of the face/bleaching and what they'll be used for? 

Once we're sure this is exactly how we need it, I'll send over two more shapes of the coral with the exact same fade approach. I just want to make sure I'm doing this with the amount of phases/face styles/etc. that you want first before I replicated it wrong two more times.

**Comment by andyroberson** [comment]
I asked for other variations of coral because I was guessing there might be occasions when the coral is sad but maybe not bleached. Like if it wasn't getting enough food? Or the temperature was too cold? Is that a correct assumption?

**Comment by kristiwalker** [comment]
Nah, I think it's pretty straight forward enough that they'll always be
bleached if they're sad. Luckily, that makes it easy enough for us!

*Kristi Walker *
kristiwalker.com

**Comment by kristiwalker** [comment]
Here's the coral phases update. Making them smile gradually was nearly impossible. I did try it, and can show you that file, but it took forever and it didn't look natural. The jumpyness actually feels more like a professional animation than the other way around. If we were doing this in After Effects, we'd be solid, but manually trying to adjust the bezzys just isn't working. The eyes are really easy to move/blink BUT I realized really quickly that we want to wait and do that after we're sure the phasing is final because this Illustrator file is super buggy. Theres a really tricky thing with the 3D effect that screws up the spots easily depending on where the artboard is on the screen. It took 5 hours of copying/pasting/deleting/bandaiding just to make sure all of the spots looked the same for every phase -- I can show you when we're working together again because it's got to be an Illustrator bug that we're just gonna have to work around. I'd really like to have 3 different versions of coral, but let's just use this one for now (maybe flip the image horizontally so you can have two versions). If we can figure out that what's going on with the 3D modeling, it won't be hard for me to make 2 more original coral samples. They're numbered based on their brightness/darkness percent. It also may look like coral 40 and one other number are missing. That's because those spots wouldn't copy the same like anything else and the phasing still looked normal without them so I just had to delete them. Sorry if this doesn't make sense -- I can explain better in person. The images should be good to use, though!

![phases_coral-1-20](https://cloud.githubusercontent.com/assets/10449842/14581865/0a2b82f0-03c6-11e6-96ad-e59923d58e22.png)
![phases_coral-1-23](https://cloud.githubusercontent.com/assets/10449842/14581870/0a2fdb7a-03c6-11e6-97f5-0e5b07af2c21.png)
![phases_coral-1-26](https://cloud.githubusercontent.com/assets/10449842/14581869/0a2dd762-03c6-11e6-9077-067c2f8f74a0.png)
![phases_coral-1-30](https://cloud.githubusercontent.com/assets/10449842/14581868/0a2d6f84-03c6-11e6-9db0-387e4fa10869.png)
![phases_coral-1-33](https://cloud.githubusercontent.com/assets/10449842/14581866/0a2d07f6-03c6-11e6-9175-b1f8bb1b5ec4.png)
![phases_coral-1-36](https://cloud.githubusercontent.com/assets/10449842/14581867/0a2d473e-03c6-11e6-9e89-c43e00b13b28.png)
![phases_coral-1-43](https://cloud.githubusercontent.com/assets/10449842/14581874/0a399340-03c6-11e6-896a-8ab0d03d7daa.png)
![phases_coral-1-46](https://cloud.githubusercontent.com/assets/10449842/14581871/0a389a9e-03c6-11e6-9c11-3f4087647cbb.png)
![phases_coral-1-50](https://cloud.githubusercontent.com/assets/10449842/14581875/0a3a2b2a-03c6-11e6-9928-2b226588e890.png)
![phases_coral-1-56](https://cloud.githubusercontent.com/assets/10449842/14581872/0a3934f4-03c6-11e6-82df-69ee4cd25ac3.png)
![phases_coral-1-60](https://cloud.githubusercontent.com/assets/10449842/14581873/0a39a6fa-03c6-11e6-9a73-4e26ca7cebe0.png)
![phases_coral-1-63](https://cloud.githubusercontent.com/assets/10449842/14581876/0a3b39ac-03c6-11e6-8619-4436abe85de6.png)
![phases_coral-1-66](https://cloud.githubusercontent.com/assets/10449842/14581878/0a416bec-03c6-11e6-9260-af349c2d9abb.png)
![phases_coral-1-70](https://cloud.githubusercontent.com/assets/10449842/14581879/0a41aeea-03c6-11e6-85f4-f03c411475b0.png)
![phases_coral-1-73](https://cloud.githubusercontent.com/assets/10449842/14581877/0a415b48-03c6-11e6-8dba-5823c69ce97b.png)
![phases_coral-1-76](https://cloud.githubusercontent.com/assets/10449842/14581880/0a41d26c-03c6-11e6-8a39-9e7b6f18cafc.png)
![phases_coral-1-80](https://cloud.githubusercontent.com/assets/10449842/14581881/0a42d2fc-03c6-11e6-945e-90d5988710cb.png)
![phases_coral-1-83](https://cloud.githubusercontent.com/assets/10449842/14581882/0a4375b8-03c6-11e6-9306-13b9cbe1d36d.png)
![phases_coral-1-86](https://cloud.githubusercontent.com/assets/10449842/14581883/0a49b504-03c6-11e6-81aa-50b4235dacd1.png)
![phases_coral-1-90](https://cloud.githubusercontent.com/assets/10449842/14581884/0a49acb2-03c6-11e6-9ab1-3f96bbd43958.png)
![phases_coral-1-93](https://cloud.githubusercontent.com/assets/10449842/14581885/0a4a0180-03c6-11e6-97eb-3ec3d3c9ec52.png)
![phases_coral-1-96](https://cloud.githubusercontent.com/assets/10449842/14581886/0a4a8c68-03c6-11e6-8539-59e8348e925f.png)
![phases_coral-1-100](https://cloud.githubusercontent.com/assets/10449842/14581887/0a4aa31a-03c6-11e6-89dc-71cd3dec6821.png)
